### ISSUE TITLE
How to create a new function just as an alias of one that already exists.

### ISSUE THREAD

**Issue by cecab** [xapix-io/axel-f#41]
This is not a bug request, it is a feature request. 

Due to language differences, o platforms to run Spreadsheets functions, I would like to ask about to implement an "alias mechanism" , for example, I need the function CONCAT(...) which is exactly the same as CONCATENATE, having a way to aliasing the function name, would make easier to run AXEL-F in different context, like Google Spreadsheets.

I would like to try to implement it, but first I want some pointers, o opinion about where in the code should be the best place to add this feature.

**Comment by DeLaGuardo** [comment]
Please take a look on that [PR](https://github.com/xapix-io/axel-f/pull/39)

There is a new way how to define a function for axel-f parser.

In your specific case it is possible to reuse same implementation by adding multimethod:

```
(defmethod axel-f.macros/find-impl "CONCAT" [_]
  (get-method axel-f.macros/find-impl "CONCATENATE"))
```

**Comment by DeLaGuardo** [comment]
Done in #39
