### ISSUE TITLE
Vectors as arguments

### ISSUE THREAD

**Issue by DeLaGuardo** [xapix-io/axel-f#5]
Some functions like SUM, LEN or CONCATENATE accept vectors as an arguments.

Example:
Context:
```clojure
{:foo {:bar {:baz [4 5 6]}}}
```

`SUM(1, foo.bar.baz, 5)`
`LEN(foo.bar.baz)`
`LEN(["x", "c", "v"])`

**Comment by mreinsch** [comment]
this is already implemented - @DeLaGuardo please close
