### ISSUE TITLE
Field reference with space results in exception

### ISSUE THREAD

**Issue by kennyjwilli** [xapix-io/axel-f#51]
According to the [docs](https://github.com/xapix-io/axel-f#object-references), I can use a field reference with a space by wrapping into `#''`. I tried this and received an exception: 

```clojure
((axel-f/compile "SUM(1, #'my var')")
  {"my var" 3})
Execution error (ExceptionInfo) at axel_f.runtime$eval3129$fn__3132/doInvoke (runtime.cljc:230).
Error in function `SUM`
```

**Comment by DeLaGuardo** [comment]
Thanks! This is definitely a regression. I made a PR with a fix https://github.com/xapix-io/axel-f/pull/53

Bwt with most recent version of axel-f you can use backslash as a "escape next character" to achieve the same result. 
```
((axel-f/compile "SUM(1, foo\\ bar)") {"foo bar" 1}) ;; => 2
((axel-f/compile "SUM(1, foo\\ bar.baz)") {"foo bar" {:baz 1}}) ;; => 2
```
