### ISSUE TITLE
Multi-line formulas

### ISSUE THREAD

**Issue by kennyjwilli** [xapix-io/axel-f#52]
Are multi-line formulas something you would be interested in supporting?

**Comment by DeLaGuardo** [comment]
Are you talking about that kind of multiline formulas?
https://github.com/xapix-io/axel-f/blob/eea54ed66212be2c4fb7dee40af178696b2dfe9a/test/axel_f/parser_test.cljc#L296-L299

**Comment by kennyjwilli** [comment]
Yes. Here's the example I tried that failed: 
```clojure
((axel-f/compile
   "SUM(1,
        2)"))
Execution error (ExceptionInfo) at axel_f.runtime$eval3429$fn__3432/doInvoke (runtime.cljc:230).
Error in function `SUM`
```

**Comment by DeLaGuardo** [comment]
Please try 1.0.3-SNAPSHOT there is a fix for that. I will release it till the end of this week.

**Comment by DeLaGuardo** [comment]
merged in master
