### ISSUE TITLE
Object functions

### ISSUE THREAD

**Issue by DeLaGuardo** [xapix-io/axel-f#58]

**Comment by mreinsch** [comment]
added in https://github.com/xapix-io/axel-f/commit/52d02bf259fd759cfdf2f987dd9f521c2656ddb7 - but needs some documentation

**Comment by mreinsch** [comment]
latest version: https://github.com/xapix-io/axel-f/blob/master/src/axel_f/functions/object.cljc

**Comment by DG4227** [comment]
Blocked by https://app.zenhub.com/workspaces/-xapix-core-5b09a99276f98d26207426b2/issues/xapix-io/phoenix/2254
