### ISSUE TITLE
NULL is considered a var

### ISSUE THREAD

**Issue by kennyjwilli** [xapix-io/axel-f#67]
`analyze` considers `NULL` a variable, which seems incorrect to me. 

```clojure
(axel-f/analyze "NULL")
=> {:vars (("NULL"))}
```

I would've expected `{:vars ()}` as the result. Is this a bug or an expected behavior?

**Comment by DeLaGuardo** [comment]
I did not have time to finalize analyzer's api. There are a lot of things to improve. 

Right now I'm focused on compile-time and runtime performance. You can check progress here - https://github.com/xapix-io/axel-f/pull/66
In that PR NULL and Booleans already become real constants and not a variables that should be resolved in runtime.

**Comment by DeLaGuardo** [comment]
In #66 analyzer is embedded into compiler. So all compiled formulas will have metadata with `:free-variables` key inside. I think that interface is much better than separate namespace. Please check it out (specifically https://github.com/xapix-io/axel-f/blob/next-generation/test/axel_f/extract_context_test.cljc) and share your concerns

**Comment by kennyjwilli** [comment]
This is fixed in the latest version 2.0.2. Thanks!
